/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LivingGodCoin } from './LivingGodCoin.js';
export * as factories from './factories/index.js';
export { LivingGodCoin__factory } from './factories/LivingGodCoin__factory.js';